import { ThemeI } from "../theme/contracts/theme";
export declare const baseThemeConfigPrimaryFont: string;
export declare const baseThemeConfigAccentFont: string;
export declare const baseThemeConfigSupportingFont: string;
export declare const baseThemeConfigScaleXs: string;
export declare const baseThemeConfigScaleSm: string;
export declare const baseThemeConfigScaleMd: string;
export declare const baseThemeConfigScaleLg: string;
export declare const baseThemeConfigScaleXl: string;
export declare const baseThemeConfigScale2Xl: string;
export declare const baseThemeConfigScale3Xl: string;
export declare const baseThemeConfigScale4Xl: string;
export declare const baseThemeConfigScale5Xl: string;
export declare const baseThemeConfigScale6Xl: string;
export declare const baseThemeConfigScale7Xl: string;
export declare const baseThemeConfigScale8Xl: string;
export declare const baseThemeConfigScale9Xl: string;
export declare const baseThemeConfigRadiusXs: string;
export declare const baseThemeConfigRadiusSm: string;
export declare const baseThemeConfigRadiusMd: string;
export declare const baseThemeConfigRadiusLg: string;
export declare const baseThemeConfigRadiusXl: string;
export declare const baseThemeConfigRadius2Xl: string;
export declare const baseThemeConfigRadius3Xl: string;
declare const BaseTheme: ThemeI;
export { BaseTheme };
