name: Publish

on:
  push:
    tags:
      - '*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                persist-credentials: false

            - name: Publish to npm
              uses: JS-DevTools/npm-publish@v1
              with:
                token: ${{ secrets.NPM_TOKEN }}

